config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: { omniauth_callbacks: 'players/omniauth_callbacks' }
  root 'static_pages#index'
  mount ActionCable.server => '/cable'
  resources :games do
    put '/castle' => 'special_moves#castle'
  end
  resources :pieces, only: :update
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<!-- Banner -->
<section id="banner">
	<div class="inner">
		<div class="logo"><%= image_tag 'whiteknight.png', class: 'icon' %></div>
		<h2>Firehose Chess Senders!</h2>
		<p>A paragraph about Chess Sending goes here... Is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
    <header>
      <nav id='primary_navigation'>
        <% if player_signed_in? %>
          <%= link_to 'Join Game', games_path %>
          <%= link_to 'Create Game', new_game_path, method: :get %>
          <%= link_to 'Sign Out', destroy_player_session_path(current_player), method: :delete %>
        <% else %>
          <%= link_to 'Sign up', new_player_registration_path, class: 'button primary' %>
          <%= link_to 'Log in', new_player_session_path, class: 'button' %>
          <%= link_to player_facebook_omniauth_authorize_path, class: 'button' do %>
            <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x icon-background"></i>
            <i class="fa fa-facebook icon fa-stack-1x"></i>
            </span>
            <span>Log in with Facebook</span>
          <% end %>
          <%= link_to player_google_oauth2_omniauth_authorize_path, class: 'button' do %>
          <span class="fa-stack">
            <i class="fa fa-circle fa-stack-2x icon-background"></i>
            <i class="fa fa-google icon fa-stack-1x"></i>
          </span>
          <span>Log in with Google</span>
          <% end %>
        <% end %>
      </nav>
    </header>
	</div>
</section>

<!-- Wrapper -->
<section id="wrapper">

	<!-- One -->
		<section id="one" class="wrapper spotlight style1">
			<div class="inner">
				<div class="content">
					<h2 class="major">Tested with Rspec + Capybara</h2>
					<p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
				</div>
				<a href="#" class="image"><%= image_tag 'code.png' %></a>
			</div>
		</section>

	<!-- Two -->
		<section id="two" class="wrapper alt spotlight style2">
			<div class="inner">
				<div class="content">
					<h2 class="major">Slim controllers & models with Service Objects</h2>
					<p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
				</div>
				<a href="#" class="image"><%= image_tag 'code.png' %></a>
			</div>
		</section>

	<!-- Three -->
		<section id="three" class="wrapper spotlight style3">
			<div class="inner">
				<div class="content">
					<h2 class="major">Nullam dignissim</h2>
					<p>Lorem ipsum dolor sit amet, etiam lorem adipiscing elit. Cras turpis ante, nullam sit amet turpis non, sollicitudin posuere urna. Mauris id tellus arcu. Nunc vehicula id nulla dignissim dapibus. Nullam ultrices, neque et faucibus viverra, ex nulla cursus.</p>
				</div>
				<a href="#" class="image"><%= image_tag 'code.png' %></a>
			</div>
		</section>

		<section id="four" class="wrapper alt style1">
			<div class="inner">
				<h2 class="major">Meet the Chess Senders</h2>
				<section class="features">
					<article>
						<a href="#" class="image"><%= image_tag 'profile.png', alt: 'Adrian Chung' %></a>
					  <h3><%= link_to 'Adrian Chung', '#'%></h3>
					</article>
					<article>
						<a href="#" class="image"><%= image_tag 'profile.png', alt: 'Ben Kautt' %></a>
						<h3><%= link_to 'Ben Kautt', '#'%></h3>
					</article>
					<article>
						<a href="#" class="image"><%= image_tag 'profile.png', alt: 'Kadeem Walsh' %></a>
						<h3><%= link_to 'Kadeem Walsh', '#'%></h3>
					</article>
					<article>
						<a href="#" class="image"><%= image_tag 'profile.png', alt: 'Davey Wright' %></a>
						<h3><%= link_to 'Davey Wright', '#'%></h3>
					</article>
				</section>
			</div>
		</section>
	</section>

<!-- Tools for the Job -->
	<section class='image_row'>
		<div class="inner">
			<ul>
				<li>
					<%= image_tag 'github.png' %>
				</li>
				<li>
					<%= image_tag 'slack.png' %>
				</li>
				<li>
					<%= image_tag 'trello.png' %>
				</li>
				<li>
					<%= image_tag 'rubocop.png' %>
				</li>
			</ul>
		</div>
	</section>

<!-- Footer -->
	<section id="footer">
		<div class="inner">
			<ul class="copyright">
				<li>&copy; Untitled Inc. All rights reserved.</li>
			</ul>
		</div>
	</section>