config/routes.rb
Rails.application.routes.draw do
  devise_for :players, controllers: { omniauth_callbacks: 'players/omniauth_callbacks' }
  root 'static_pages#index'
  mount ActionCable.server => '/cable'
  resources :games do
    put '/castle' => 'special_moves#castle'
  end
  resources :pieces, only: :update
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chess</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="is-preload">
    <div id="main_wrapper">

      <div id='main'>
        <% if notice.present? %>
          <p class="alert alert-info text-center"><%= notice %></p>
        <% end %>
        <% if alert.present? %>
          <p class="alert alert-danger text-center"><%= alert %></p>
        <% end %>

        <%= yield %>
      </div>

      <% if player_signed_in? %>
        <!-- Sidebar -->
        <div id="sidebar">
          <div class="inner">
            <section class='player_dashboard'>
              <h3>// <span>Dashboard</span></h3>
              <h2><%= current_player.playername %></h2>
              <p>Last active: <%= current_player.last_sign_in_at.strftime("%b %d, %Y") %></p>
              <h3>Games</h3>
              <h3><span>Won: </span><%= current_player.games_won %></h3>
              <h3><span>Lost: </span><%= current_player.games_lost %></h3>
              <h3><span>Drawn: </span>:</span><%= current_player.games_drawn %></h3>
              <h3><span>Total played: </span><%= current_player.total_games %></h3>

            </section>
            <section class='dashboard_navigation'>
              <nav id="menu">
                <ul>
                  <li id='my_games_dropdown'>
                    <span class='opener'>My Games</span>
										<ul>
                      <% current_player.games.each do |game| %>
  											<li>
                          <%= link_to game.name, game_path(game) %>
                        </li>
                      <% end %>
										</ul>
									</li>
                  <li id='my_games_dropdown'>
                    <span class='opener'>My Active Games</span>
										<ul>
                      <% current_player.games_in_progress.each do |game| %>
  											<li>
                          <%= link_to game.name, game_path(game) %>
                        </li>
                      <% end %>
										</ul>
									</li>
                  <li><%= link_to 'Join a Game', games_path %></li>
                  <li id='create_game_dropdown'>
                    <span class='opener'>Create a Game</span>
                    <ul>
											<li>
                        <form action="#">
                  					<div class="field">
                  						<label for="game_name">Game Name</label>
                  						<input type="text" name="name" id="game_name" />
                  					</div>
                            <button id='create_game' class='primary' data-url="<%= games_path %>">create!</button>
                            <button type="reset" calue='Reset' name="button">Cancel</button>
                  			</form>
                      </li>
                    </ul>
                  </li>
                  <li><%= link_to 'Homepage', root_path %></li>
                  <li><%= link_to 'Sign Out', destroy_player_session_path, method: :delete %></li>
                </ul>
              </nav>
            </section>

          </div>
        </div>
      <% end %>

    </div>


    <script type="text/javascript">
    	$(()=>{
    		$('#create_game').click((e)=>{
          e.preventDefault();
    			$.ajax({
    				type: 'POST',
    				url: $(e.target).data('url'),
    				data: { name: $('#game_name').val() }
    			});
    		})
    	});
    </script>

  </body>
</html>